# Generated by Django 6.0.4 on 2026-07-21 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='نام برند')),
                ('url', models.CharField(max_length=80, verbose_name='آدرس برند')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/brands', verbose_name='تصویر برند')),
                ('about', models.TextField(blank=True, max_length=300, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/فعال نبودن')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='تخفیف')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('valid_from', models.DateTimeField(verbose_name='اعتبار از')),
                ('valid_until', models.DateTimeField(verbose_name='اعتبار تا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='نام دسته بندی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/categories', verbose_name='تصویر کتگوری')),
                ('url', models.CharField(max_length=80, verbose_name='آدرس دسته بندی')),
                ('about', models.TextField(blank=True, max_length=300, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.category', verbose_name='دسته بندی پدر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='نام محصول')),
                ('price', models.IntegerField(blank=True, verbose_name='قیمت محصول')),
                ('current_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='توضیحات محصول')),
                ('image', models.ImageField(blank=True, upload_to='images/products', verbose_name='تصاویر محصول')),
                ('inventory', models.IntegerField(default=0, verbose_name='موجودی در انبار')),
                ('slug', models.SlugField(blank=True, default='', max_length=150, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال یا غیرفعال')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='امتیاز محصول')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
                ('brand', models.ForeignKey(blank=True, max_length=80, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_module.brand', verbose_name='برند')),
                ('category', models.ManyToManyField(blank=True, max_length=80, to='product_module.category', verbose_name='دسته بندی')),
                ('discounted', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_module.discount', verbose_name='قیمت آف خورده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='متن کامنت')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال کامنت')),
                ('is_approved', models.BooleanField(default=True, verbose_name='مورد تایید')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='نمره به محصول')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product_module.productcomment', verbose_name='کامنت والد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product_galleries', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
            },
        ),
        migrations.CreateModel(
            name='ProductVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, verbose_name='ip')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازدید',
                'verbose_name_plural': 'بازدیدها',
            },
        ),
    ]
