# Generated by Django 6.0.4 on 2026-08-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_attribute_productattribute_product_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='product_module.productattribute', verbose_name='ویژگی های محصول'),
        ),
    ]
