# Generated by Django 6.0.4 on 2026-08-02 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_product_attributes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'ویژگی محصول', 'verbose_name_plural': 'ویژگیهای محصولات'},
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='product_module.attribute', verbose_name='ویژگی ها'),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='محتوای ویژگی')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.attribute', verbose_name='ویژگی محصول')),
            ],
            options={
                'verbose_name': 'محتوای ویژگی محصول',
                'verbose_name_plural': 'محتوای ویژگیهای محصولات',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='product_module.attributevalue', verbose_name='ویژگی های محصول'),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
