# Generated by Django 6.0.4 on 2026-09-22 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_module', '0005_alter_attribute_options_category_attributes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='نهایی شده')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('final_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت تمام شده')),
                ('final_discount', models.IntegerField(default=0, verbose_name='مبلغ تخفیف نهایی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_module.order', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'خرید محصول',
                'verbose_name_plural': 'خریدهای محصول',
            },
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='بن خرید')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد بن خرید')),
                ('amount', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('valid_from', models.DateTimeField(verbose_name='اعتبار از')),
                ('valid_until', models.DateTimeField(verbose_name='اعتبار تا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ManyToManyField(blank=True, null=True, to='product_module.product', verbose_name='فقط این محصولات')),
                ('order_item', models.ManyToManyField(blank=True, null=True, to='order_module.orderitem', verbose_name='خرید محصول')),
            ],
            options={
                'verbose_name': 'بن خرید',
                'verbose_name_plural': 'بن های خرید',
            },
        ),
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=200, verbose_name='استان')),
                ('city', models.CharField(max_length=200, verbose_name='شهر')),
                ('postal_code', models.CharField(max_length=20, verbose_name='کد پستی')),
                ('exact_address', models.CharField(max_length=200, verbose_name='آدرس دقیق')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('shipping_cost', models.IntegerField(blank=True, default=40000, null=True, verbose_name='هزینه ارسال')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_module.order', verbose_name='سبد خرید')),
            ],
            options={
                'verbose_name': 'آدرس پستی',
                'verbose_name_plural': 'آدرس های پستی',
            },
        ),
    ]
