# Generated by Django 6.0.4 on 2026-07-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_auto_20220417_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/site-setting/', verbose_name='تصویر درباره سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/site-setting/', verbose_name='لوگو سایت'),
        ),
    ]
