# Generated by Django 6.0.4 on 2026-09-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_sitesetting_picture_alter_sitesetting_site_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('email', models.EmailField(max_length=80, verbose_name='ایمیل')),
                ('message', models.TextField(max_length=200, verbose_name='متن پیام')),
                ('send_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('response', models.TextField(blank=True, max_length=200, null=True, verbose_name='پاسخ به پیام')),
                ('be_sent_email', models.BooleanField(default=False, verbose_name='ایمیل ارسال شود')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباطات با ما',
            },
        ),
    ]
