import type { Article, ArticleComment, Category, Product, ProductComment, SiteSetting } from "./types";

export const mockCategories: Category[] = [
  { id: 1, name: "الکترونیک", slug: "electronics", description: "گجت‌ها و دستگاه‌های دیجیتال" },
  { id: 2, name: "مد و پوشاک", slug: "fashion", description: "لباس، کفش و اکسسوری" },
  { id: 3, name: "خانه و آشپزخانه", slug: "home", description: "وسایل منزل و دکور" },
  { id: 4, name: "کتاب", slug: "books", description: "کتاب‌های چاپی و الکترونیک" },
];

const baseProducts: Product[] = [
  {
    id: 1,
    name: "هدفون بی‌سیم ANC",
    slug: "wireless-anc-headphones",
    description: "هدفون با کیفیت بالا با قابلیت حذف نویز فعال و باتری ۳۰ ساعته.",
    price: 2_450_000,
    compare_price: 2_890_000,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    category: mockCategories[0],
    stock: 12,
    brand: "سونی",
    colors: ["مشکی", "سفید"],
    is_available: true,
  },
  {
    id: 2,
    name: "ساعت هوشمند ورزشی",
    slug: "smart-sports-watch",
    description: "ردیاب تناسب اندام با GPS داخلی، ضربان قلب و مقاومت در برابر آب.",
    price: 1_890_000,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
    category: mockCategories[0],
    stock: 8,
    brand: "شیائومی",
    colors: ["مشکی", "نقره‌ای"],
    is_available: true,
  },
  {
    id: 3,
    name: "کت پشمی مردانه",
    slug: "mens-wool-coat",
    description: "کت گرم و شیک مناسب فصول سرد با برش مدرن.",
    price: 1_250_000,
    compare_price: 1_550_000,
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80",
    category: mockCategories[1],
    stock: 5,
    brand: "زارا",
    colors: ["سرمه‌ای", "خاکستری"],
    is_available: true,
  },
  {
    id: 4,
    name: "چراغ مطالعه LED",
    slug: "led-desk-lamp",
    description: "چراغ میز کار با تنظیم نور گرم و سرد و پایه فلزی باکیفیت.",
    price: 680_000,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80",
    category: mockCategories[2],
    stock: 20,
    brand: "فیلیپس",
    colors: ["سفید"],
    is_available: true,
  },
  {
    id: 5,
    name: "رمان «۱۹۸۴»",
    slug: "1984-book",
    description: "چاپ جدید رمان کلاسیک جورج اورول با ترجمه فارسی.",
    price: 145_000,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80",
    category: mockCategories[3],
    stock: 50,
    brand: "نشر نی",
    colors: ["کرم"],
    is_available: true,
  },
  {
    id: 6,
    name: "اسپیکر بلوتوثی قابل حمل",
    slug: "portable-bluetooth-speaker",
    description: "صدا با بیس قوی، مقاوم در برابر آب و باتری ۲۰ ساعته.",
    price: 920_000,
    compare_price: 1_100_000,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80",
    category: mockCategories[0],
    stock: 15,
    brand: "JBL",
    colors: ["مشکی", "آبی"],
    is_available: true,
  },
  {
    id: 7,
    name: "کفش کتانی زنانه",
    slug: "women-sneakers",
    description: "کفش راحت و سبک مناسب پیاده‌روی و ورزش روزمره.",
    price: 780_000,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    category: mockCategories[1],
    stock: 9,
    brand: "نایکی",
    colors: ["سفید", "صورتی"],
    is_available: true,
  },
  {
    id: 8,
    name: "ست قهوه‌ساز دستی",
    slug: "manual-coffee-maker-set",
    description: "ست فرنچ پرس، آسیاب دستی و فیلترهای قابل شستشو.",
    price: 1_100_000,
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    category: mockCategories[2],
    stock: 6,
    brand: "هاریو",
    colors: ["نقره‌ای", "مشکی"],
    is_available: true,
  },
];

const galleryPool = [
  "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80",
  "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&q=80",
  "https://images.unsplash.com/photo-1523206489230-c012c64b2b48?w=800&q=80",
];

const specsByCategory: Record<string, { label: string; value: string }[]> = {
  electronics: [
    { label: "گارانتی", value: "۱۸ ماه شرکتی" },
    { label: "اتصال", value: "بلوتوث ۵.۳" },
    { label: "باتری", value: "۳۰ ساعت پخش مداوم" },
    { label: "وزن", value: "۲۵۰ گرم" },
  ],
  fashion: [
    { label: "جنس", value: "پشم و پلی‌استر" },
    { label: "اندازه‌ها", value: "S تا XXL" },
    { label: "فصل", value: "پاییز و زمستان" },
    { label: "شستشو", value: "خشک‌شویی" },
  ],
  home: [
    { label: "جنس بدنه", value: "استیل ضد زنگ" },
    { label: "ابعاد", value: "۲۰ × ۱۲ × ۱۲ سانتی‌متر" },
    { label: "ظرفیت", value: "۶۰۰ میلی‌لیتر" },
    { label: "قابل شستشو", value: "بله" },
  ],
  books: [
    { label: "نویسنده", value: "جورج اورول" },
    { label: "مترجم", value: "صالح حسینی" },
    { label: "سال تألیف", value: "۱۹۴۹" },
    { label: "تعداد صفحات", value: "۳۲۰ صفحه" },
  ],
};

export const mockProducts: Product[] = baseProducts.map((product) => ({
  ...product,
  images: [product.image!, ...galleryPool],
  rating: 3.8 + ((product.id * 3) % 12) / 10,
  reviews_count: 4 + ((product.id * 7) % 23),
  specs: specsByCategory[product.category?.slug ?? "home"] ?? [],
}));

export const mockArticles: Article[] = [
  {
    id: 1,
    title: "راهنمای خرید هدفون بی‌سیم",
    slug: "wireless-headphones-guide",
    author: "علی رضایی",
    short_description: "قبل از خرید هدفون بی‌سیم، این نکات کلیدی را بدانید.",
    content:
      "هنگام انتخاب هدفون بی‌سیم به عمر باتری، کیفیت حذف نویز فعال، تأخیر صدا و پشتیبانی از کدک‌های باکیفیت مانند LDAC و aptX توجه کنید. راحتی طولانی مدت و وزن نیز اهمیت زیادی دارد.\n\nپیشنهاد ما این است که ابتدا کاربری اصلی خود را مشخص کنید: موسیقی، تماس یا ورزش. سپس بودجه را تعیین و مدل‌های محبوب همان رده را مقایسه کنید.",
    pub_date: "2025-04-12T09:00:00Z",
    category: "الکترونیک",
    image: "https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?w=1200&q=80",
    is_published: true,
  },
  {
    id: 2,
    title: "ترندهای مد پاییز امسال",
    slug: "autumn-fashion-trends",
    author: "مریم کریمی",
    short_description: "جدیدترین رنگ‌ها، برش‌ها و استایل‌های پاییزی که باید امتحان کنید.",
    content:
      "پاییز امسال رنگ‌های زمینی مثل قهوه‌ای سوخته، زیتونی و کِرِم پررنگ محبوبیت زیادی دارند. کت‌های آزاد با برش‌های بلند، شلوارهای گشاد و بوت‌های ساقه‌بلند از پرتکرارترین قطعه‌های استایل هستند.\n\nترکیب لایه‌ای همیشه جواب می‌دهد: یک تی‌شرت پایه، پیراهن نازک و کت بلند می‌تواند یک استایل تمام‌عیار بسازد.",
    pub_date: "2025-05-02T11:30:00Z",
    category: "مد و پوشاک",
    image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200&q=80",
    is_published: true,
  },
  {
    id: 3,
    title: "چیدمان مینیمال برای خانه‌های کوچک",
    slug: "minimal-home-small-spaces",
    author: "سارا موسوی",
    short_description: "با چند ترفند ساده، خانه کوچک را بزرگ‌تر و دلبازتر نشان دهید.",
    content:
      "پالت رنگی روشن، نور طبیعی و مبلمان چندکاره سه پایه اصلی چیدمان مینیمال هستند. آینه‌ها را روبروی پنجره قرار دهید تا نور بازتاب یابد و فضا بزرگ‌تر به نظر برسد.\n\nاز قفسه‌های دیواری برای آزاد کردن سطح زمین استفاده کنید و رنگ‌های تاکیدی را در حد یک یا دو قطعه نگه دارید.",
    pub_date: "2025-06-18T14:00:00Z",
    category: "خانه و آشپزخانه",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200&q=80",
    is_published: true,
  },
  {
    id: 4,
    title: "پنج کتاب که هر علاقه‌مند به تکنولوژی باید بخواند",
    slug: "top-5-tech-books",
    author: "امیر صادقی",
    short_description: "لیستی از کتاب‌هایی که نگاه شما به تکنولوژی را تغییر می‌دهد.",
    content:
      "از «سریع و آهسته فکر کن» دنیل کانمن تا «انسان خردمند» یووال نوح هراری، این پنج کتاب چارچوب فکری تازه‌ای درباره تصمیم‌گیری، فناوری و آینده ارائه می‌دهند.\n\nخواندن این کتاب‌ها به شما کمک می‌کند فراتر از خبرها به روندهای بلندمدت نگاه کنید.",
    pub_date: "2025-07-10T08:15:00Z",
    category: "کتاب",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=1200&q=80",
    is_published: true,
  },
];

export const mockArticleComments: ArticleComment[] = [
  {
    id: 1,
    article: 1,
    user: "reza",
    text: "مقاله خیلی مفیدی بود، ممنون از توضیحات کامل!",
    create_date: "2025-04-13T10:00:00Z",
    is_approved: true,
    parent: null,
  },
  {
    id: 2,
    article: 1,
    user: "nazanin",
    text: "کدام مدل رو برای ورزش پیشنهاد می‌کنید؟",
    create_date: "2025-04-14T12:30:00Z",
    is_approved: true,
    parent: null,
  },
  {
    id: 3,
    article: 1,
    user: "admin",
    text: "برای ورزش هدفون‌های in-ear با محافظ گوش گزینه بهتری هستن.",
    create_date: "2025-04-14T15:00:00Z",
    is_approved: true,
    parent: 2,
  },
  {
    id: 4,
    article: 2,
    user: "sara",
    text: "رنگ‌های زمینی همیشه شیک‌ن.",
    create_date: "2025-05-03T09:00:00Z",
    is_approved: true,
    parent: null,
  },
];

export const mockProductComments: ProductComment[] = [
  {
    id: 1,
    product: 1,
    user: "ali",
    text: "کیفیت صدا فوق‌العاده‌ست، حذف نویز عالی کار می‌کنه.",
    create_date: "2025-03-10T09:00:00Z",
    is_approved: true,
    parent: null,
    rate: 5,
  },
  {
    id: 2,
    product: 1,
    user: "mina",
    text: "باتری واقعا ۳۰ ساعت دووم میاره؟",
    create_date: "2025-03-12T10:30:00Z",
    is_approved: true,
    parent: null,
    rate: 4,
  },
  {
    id: 3,
    product: 1,
    user: "ali",
    text: "بله تقریبا ۲۸ ساعت با ANC روشن.",
    create_date: "2025-03-12T14:00:00Z",
    is_approved: true,
    parent: 2,
    rate: 5,
  },
  {
    id: 4,
    product: 2,
    user: "hamed",
    text: "برای دویدن عالیه، GPSش دقیقه.",
    create_date: "2025-04-01T08:00:00Z",
    is_approved: true,
    parent: null,
    rate: 5,
  },
];

export const mockSiteSetting: SiteSetting = {
  site_name: "فروشگاه",
  site_url: "https://example.com",
  address: "تهران، خیابان ولیعصر، پلاک ۱۲۰",
  phone: "۰۲۱-۱۲۳۴۵۶۷۸",
  fax: "۰۲۱-۱۲۳۴۵۶۷۹",
  email: "info@example.com",
  copy_right: "تمامی حقوق برای فروشگاه محفوظ است.",
  about_us_text:
    "ما یک فروشگاه آنلاین هستیم که با هدف ساده‌تر کردن تجربه خرید، محصولات باکیفیت را با قیمت منصفانه و ارسال سریع در اختیار شما قرار می‌دهیم.\n\nتیم ما از سال ۱۳۹۸ فعالیت خود را آغاز کرده و امروز به هزاران مشتری در سراسر کشور خدمات می‌دهد. رضایت شما مهم‌ترین معیار ماست.",
  is_main_setting: true,
};
