# Generated by Django 6.0.4 on 2026-09-21 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='نام دسته بندی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/categories', verbose_name='تصویر کتگوری')),
                ('slug', models.CharField(max_length=80, verbose_name='آدرس دسته بندی')),
                ('about', models.TextField(blank=True, max_length=300, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecategory', verbose_name='دسته بندی پدر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='تیتر مقاله')),
                ('content', models.TextField(blank=True, verbose_name='متن مقاله')),
                ('short_description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('image', models.ImageField(blank=True, upload_to='images/articles/', verbose_name='تصویر مقاله')),
                ('is_published', models.BooleanField(default=True, verbose_name='انتشار یافتن')),
                ('slug', models.SlugField(blank=True, default='', max_length=150, unique=True, verbose_name='عنوان در url')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ManyToManyField(blank=True, to='article_module.articlecategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
            },
        ),
    ]
